# -*- coding: utf-8 -*-
"""Emit results/_rev/NUMBERS.md: every number added in the revision, the file that
produces it, and its seed.

Reviewer C5 asked for a number-to-file mapping inside the package, and the Methods promise
one ("Every reported number is mapped to the file that produces it, and to its seed, in the
replication package").  The file is generated from the artefacts so that it cannot drift
from them by transcription.

The real panel's own side of every comparison is recomputed here through the same code path
the null panels went through (_panel_stats in _rev_night.py), so the contrast in
Section "What the recurrence does and does not establish" is auditable rather than copied
out of the prose.

usage:  python scripts/revision/_rev_numbers.py
"""
import collections
import io
import json
import os
import sys

import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
sys.stdout.reconfigure(encoding='utf-8', errors='replace')
import _rev_lib as L  # noqa: E402

D = L.REV
TAU = float(L.TAU)


def load(f):
    p = os.path.join(D, f)
    if not os.path.exists(p):
        return None
    return json.load(io.open(p, encoding='utf-8'))


def fnum(x, nd=3):
    if x is None:
        return 'n/a'
    if isinstance(x, float):
        return ('%.*f' % (nd, x)).rstrip('0').rstrip('.')
    return str(x)


def mean(v):
    return sum(v) / float(len(v)) if v else float('nan')


def mn(v, nd=3):
    return 'n/a' if not v else (('%.*f' % (nd, min(v))).rstrip('0').rstrip('.')) if isinstance(min(v), float) else str(min(v))


def mx(v, nd=3):
    return 'n/a' if not v else (('%.*f' % (nd, max(v))).rstrip('0').rstrip('.')) if isinstance(max(v), float) else str(max(v))


L_ = []
W = L_.append

W('# Numbers added in the revision, and where each one comes from')
W('')
W('Generated by `scripts/revision/_rev_numbers.py` from the artefacts in `results/_rev/`,')
W('so the table cannot drift from the files it describes.  Seeds are those the scripts')
W('print; every run is deterministic.')
W('')

man = load('_manifest.json')
if man:
    W('## Stage ledger (`results/_rev/_manifest.json`)')
    W('')
    W('| stage | status | finished | note |')
    W('|:--|:--|:--|:--|')
    for k, v in man.items():
        W('| `%s` | %s | %s | %s |' % (k, 'ok' if v.get('ok') else 'FAILED',
                                       v.get('at', ''), v.get('note', '')))
    W('')

# --- composition (B1) -------------------------------------------------------
c = load('composition.json')
if c and 'summary' in c:
    s = c['summary']
    W('## Composition adjustment (`composition.json`, `_rev_night.py composition`, no seed -- deterministic)')
    W('')
    W('Each panel gene residualised on the 22-marker non-malignant score, all 33 cohorts refitted.')
    W('')
    W('| quantity | value |')
    W('|:--|:--|')
    W('| recurring pairs retained (>=10 cohorts) | %s of 14 |' % s.get('recurring_ge10_residual'))
    W('| shared median matrix, edges above tau | %s (was 6) |' % s.get('median_edges_residual'))
    W('| largest median coefficient | %s (was 0.731) |'
      % fnum(s.get('max_abs_median_residual')))
    pt = s.get('pair_table') or []
    W('| pairs with a raw/adjusted pair | %d |' % len(pt))
    W('')

# --- bootstrap / multiinit (A-M1) -------------------------------------------
for fn, label, seednote in [('bootstrap.json', 'Sample bootstrap', 'seed 7 + cohort index, B = 6'),
                            ('multiinit.json', 'Random re-initialisation', 'seed 555 + 100*cohort index, 6 inits, 20 cohorts')]:
    o = load(fn)
    if not o or 'summary' not in o:
        continue
    sm = o['summary']
    if fn == 'bootstrap.json':
        vals = [r['orientation_retention'] for r in sm
                if r.get('orientation_retention') is not None]
        skel = [r['skeleton_retention'] for r in sm
                if r.get('skeleton_retention') is not None]
        same = sum(1 for r in sm if r.get('orientation_retention') == r.get('skeleton_retention'))
        rev = []
    else:
        vals = [r['init_agreement'] for r in sm if r.get('init_agreement') is not None]
        skel, same, rev = [], 0, []
    if not vals:
        continue
    W('## %s (`%s`)' % (label, fn))
    W('')
    W('Seeds: %s.' % seednote)
    W('')
    W('| quantity | value |')
    W('|:--|:--|')
    W('| pairs measured | %d |' % len(vals))
    W('| mean retention / agreement | %s |' % fnum(mean(vals)))
    W('| range | %s -- %s |' % (fnum(min(vals)), fnum(max(vals))))
    if skel:
        W('| pairs where orientation retention == skeleton retention | %d of %d |'
          % (same, len(skel)))
    W('')

# --- lamscan (A-M3) ---------------------------------------------------------
o = load('lamscan.json')
if o:
    W('## Threshold grid (`lamscan.json`, `_rev_night.py lamscan`)')
    W('')
    W('tau is a post-hoc threshold, so only lambda is refitted.  Seeds: default per-cohort.')
    W('')
    W('| lambda_1 | tau | shared edges above tau | recurring pairs (>=10) |')
    W('|:--|:--|:--|:--|')
    for lam in sorted(o):
        for tau in sorted(o[lam], key=float):
            r = o[lam][tau]
            W('| %s | %s | %s | %s |' % (lam, tau, r.get('median_edges'), r.get('recurring_ge10')))
    W('')

# --- rotation (A-M2b) -------------------------------------------------------
o = load('rotation.json')
if o and o.get('rows'):
    W('## Covariance-preserving rotation null (`rotation.json`, `_rev_night.py rotation`)')
    W('')
    W('Seeds %s.' % ', '.join(str(r['seed']) for r in o['rows']))
    W('')
    W('| rep | seed | shared edges above tau | recurring pairs (>=10) | collision statistic Q |')
    W('|:--|:--|:--|:--|:--|')
    for r in o['rows']:
        W('| %d | %d | %s | %s | %s |' % (r['rep'], r['seed'], r['median_edges'],
                                          r['recurring_ge10'], fnum(r['q'], 0)))
    W('')

# --- random panels (A-M2a/b) ------------------------------------------------
fam = {}
for fn, label, seednote in [('randompanel.json', 'Mean-expression-matched panels', 'seeds 1001..1012'),
                            ('randompanel_dm.json', 'Expression- and dispersion-matched panels', 'seeds 2001..2012')]:
    o = load(fn)
    if not o or not o.get('rows'):
        continue
    rows = o['rows']
    fam[fn] = rows
    W('## %s (`%s`)' % (label, fn))
    W('')
    W('Seeds: %s.  Drawn without replacement, each real panel gene replaced by a gene in the same decile(s).' % seednote)
    W('')
    W('| pan | seed | shared edges above tau | largest median coef | pairs recurring (>=10) | pairs |')
    W('|:--|:--|:--|:--|:--|:--|')
    for r in rows:
        W('| %d | %s | %s | %s | %s | %s |'
          % (r.get('panel', -1), r.get('seed', ''), r.get('median_edges'),
             fnum(r.get('max_abs_median')), r.get('recurring_ge10'),
             '; '.join(r.get('pairs', [])[:3])))
    rec = [r['recurring_ge10'] for r in rows]
    me = [r['median_edges'] for r in rows]
    mm = [r['max_abs_median'] for r in rows]
    W('')
    W('Across the %d panels: recurring pairs at >=10 cohorts %s--%s (mean %s); shared edges above tau '
      '%s--%s (mean %s); largest median coefficient %s--%s.'
      % (len(rows), min(rec), max(rec), fnum(mean(rec), 2), min(me), max(me),
         fnum(mean(me), 2), fnum(min(mm)), fnum(max(mm))))
    pp = collections.Counter()
    for r in rows:
        for p in r.get('pairs', []):
            pp[p.split('(')[0]] += 1
    shared = sum(1 for v in pp.values() if v > 1)
    W('')
    W('Distinct recurring pair-strings %d; of these, %d appear in more than one panel.'
      % (len(pp), shared))
    if shared:
        W('')
        W('| pair | panels |')
        W('|:--|:--|')
        for k, v in pp.most_common(10):
            if v > 1:
                W('| %s | %d of %d |' % (k, v, len(rows)))
    W('')

# --- real panel, same code path as the nulls --------------------------------
real = None
try:
    fits, cs = L.load_fits('_shared_panel_notears.json')
    panel = L.load_panel()['panel']
    Ws = {x: np.array(fits[x]['W']) for x in cs}
    Mr = np.stack([np.abs(Ws[x]).astype(float) for x in cs], axis=0)
    med = np.median(Mr, axis=0)
    np.fill_diagonal(med, 0.0)
    pr = L.recurrence(Mr, TAU)
    rec = L.recurrence_list(pr, panel, 10)
    real = dict(median_edges=int((med > TAU).sum()), max_abs_median=float(med.max()),
                recurring_ge10=len(rec),
                total_edges=int(sum(fits[x]['edges'] for x in cs)))
except Exception as e:  # noqa: BLE001
    W('*(real-panel statistics unavailable: %s)*' % e)
    W('')

if real and fam:
    allnull = [r for k in fam for r in fam[k]]
    W('## Real panel against the constructed nulls (same code path as the null rows above)')
    W('')
    W('| quantity | real panel | null panels (min--max) | real beats | rank p |')
    W('|:--|:--|:--|:--|:--|')
    for key in ('median_edges', 'max_abs_median', 'recurring_ge10'):
        vals = [r[key] for r in allnull]
        beat = sum(1 for v in vals if real[key] > v)
        W('| %s | %s | %s--%s | %d of %d | <= %s |'
          % (key, fnum(real[key]), mn(vals), mx(vals), beat, len(vals),
             fnum(1.0 / (len(vals) + 1), 3)))
    W('')
    W('Real panel totals: %d edges over the 33 cohorts, %d recurring pairs (>=10 cohorts).'
      % (real['total_edges'], real['recurring_ge10']))
    W('')

# --- lowmad (A-M4) ----------------------------------------------------------
o = load('lowmad.json')
if o:
    W('## Low-dispersion control panel (`lowmad.json`, `_rev_night.py lowmad`, seed 4242)')
    W('')
    W('| quantity | value |')
    W('|:--|:--|')
    W('| median MAD percentile of the panel | %s |' % fnum(o.get('median_mad_pct')))
    W('| shared edges above tau | %s |' % o.get('median_edges'))
    W('| largest median coefficient | %s |' % fnum(o.get('max_abs_median')))
    W('| pairs recurring at >=10 cohorts | %s %s |' % (o.get('recurring_ge10'), o.get('pairs')))
    W('| total edges over 33 cohorts | %s |' % o.get('total_edges'))
    W('')

# --- dscan (A-M6) -----------------------------------------------------------
o = load('dscan.json')
if o:
    W('## Panel-width scan, real data (`dscan.json`)')
    W('')
    W('| d | total edges | Pearson r(n, edges) |')
    W('|:--|:--|:--|')
    for k in sorted(o, key=lambda s: int(s[1:])):
        r = o[k]
        W('| %s | %s | %s |' % (r['d'], r['total_edges'], fnum(r['pearson_r'])))
    W('')
o = load('dscan_null.json')
if o:
    W('## Panel-width scan, shuffled labels (`dscan_null.json`, `_rev_night.py dscan_null`, seed 71 + 1000*cohort + d)')
    W('')
    W('This is the quantity that locates the floor: on shuffled labels every returned edge is an')
    W('artefact, so the transition from cohorts that still return edges to cohorts that return none')
    W('brackets the identifiability boundary at that width.')
    W('')
    W('| d | total edges on shuffled data | Pearson r(n, edges) | max n still returning edges | min n returning none | n*/d |')
    W('|:--|:--|:--|:--|:--|:--|')
    for k in sorted(o, key=lambda s: int(s[1:])):
        r = o[k]
        W('| %s | %s | %s | %s | %s | %s |'
          % (r['d'], r['total_edges'], fnum(r['pearson_r']),
             r.get('max_n_with_edges'), r.get('min_n_without_edges'),
             fnum(r.get('boundary_over_d'), 2)))
    W('')
    W('The ratio is not constant across widths, which is why the manuscript states the floor as a')
    W('boundary measured at each width rather than as a fixed multiple of d.  The original single-')
    W('width shuffle reported in `results/_shared_panel_notears.json` gives n = 156 / 172 at d = 100;')
    W('the rerun above, at a different seed, gives n = 122 / 156 at the same width.')
    W('')

# --- mp per cohort (A-M11) --------------------------------------------------
o = load('mp_percohort.json')
if o:
    s = o['summary']
    W('## Per-cohort spectral position (`mp_percohort.json`, `_rev_mp.py`, seed %d, %d permutation controls)'
      % (o['seed'], o['n_null']))
    W('')
    W('| quantity | value |')
    W('|:--|:--|')
    W('| cohorts with leading eigenvalue above their own MP edge | %s of %s |'
      % (s['n_ratio_above_1'], s['n_cohorts']))
    W('| ratio range | %s -- %s (median %s) |' % (fnum(s['ratio_min']), fnum(s['ratio_max']), fnum(s['ratio_median'])))
    W('| ratio range, full-rank cohorts only | %s -- %s |'
      % (fnum(s['ratio_min_full_rank']), fnum(s['ratio_max_full_rank'])))
    W('| rank-deficient cohorts (n <= d) | %s |' % s['n_rank_deficient'])
    W('| cohorts whose leading eigenvalue exceeds the largest of their permutation controls | %s |'
      % s['n_lam1_above_null_max'])
    W('')

# --- survival (A-M10 / B4) --------------------------------------------------
o = load('survival_perSD.json')
if o:
    W('## Survival, continuous per-SD Cox (`survival_perSD.json`)')
    W('')
    W('| cohort | gene | n | events | HR per SD | 95% CI | p | PH p | q (BH) |')
    W('|:--|:--|:--|:--|:--|:--|:--|:--|:--|')
    for r in o['rows']:
        W('| %s | %s | %s | %s | %s | %s--%s | %s | %s | %s |'
          % (r['cohort'], r['gene'], r['n'], r['events'], fnum(r['hr_per_sd']),
             fnum(r['ci_lo']), fnum(r['ci_hi']), fnum(r['p_per_sd'], 4),
             fnum(r.get('ph_p'), 3), fnum(r.get('q_bh'), 4)))
    W('')
    W('FDR-significant hubs: %s of %s.  PH violations: %s.  Floor sensitivity: %s.'
      % (o['n_fdr_significant'], o['n_nominated'], o['n_ph_violations'],
         ', '.join('%s->%d hubs %s' % (k, v['n_hubs'], v['genes']) for k, v in o['floor_sensitivity'].items())))
    W('')

# --- trrust (B3) ------------------------------------------------------------
o = load('trrust_overlap.json')
if o:
    W('## TRRUST overlap (`trrust_overlap.json`, reported as a negative result)')
    W('')
    W('| quantity | value |')
    W('|:--|:--|')
    W('| inferred undirected pairs | %s |' % o['n_causal_pairs'])
    W('| TRRUST pairs | %s |' % o['trrust_pairs'])
    W('| hits | %s %s |' % (o['hits'], o['hit_pairs']))
    W('| random pairs drawn / hits | %s / %s |' % (o['random_pairs_drawn'], o['random_hits']))
    W('| observed vs expected rate (%% of pairs) | %s vs %s |'
      % (fnum(o['observed_rate_pct'], 4), fnum(o['expected_rate_pct'], 4)))
    W('| Fisher p | %s |' % fnum(o['fisher_p'], 8))
    W('')

# --- two-stage on real data (C3 bonus) --------------------------------------
o = load('two_stage_tcga.json')
if o:
    W('## Stage-2 projection on the real panel (`two_stage_tcga.json`, `_rev_extra.py`)')
    W('')
    W('| quantity | value |')
    W('|:--|:--|')
    W('| h(W-bar) before vs after | %s -> %s |' % (fnum(o['h_median_before'], 5), fnum(o['h_shared_after'], 5)))
    W('| h after, textbook AL schedule | %s |' % fnum(o['h_shared_after_standard_AL'], 8))
    W('| edges above tau, projected positions identical | %s / %s |'
      % (o['shared_edges_projected'], o['projected_edge_positions_identical']))
    W('| per-cohort h (min / median / max) | %s / %s / %s |'
      % (fnum(o['h_per_cohort']['min'], 5), fnum(o['h_per_cohort']['median'], 5),
         fnum(o['h_per_cohort']['max'], 5)))
    W('| cohort-specific share of a cohort\'s edges | mean %s, range %s--%s |'
      % (fnum(o['delta_summary']['cohort_specific_frac_mean']),
         fnum(o['delta_summary']['cohort_specific_frac_min']),
         fnum(o['delta_summary']['cohort_specific_frac_max'])))
    W('| Frobenius norm of Delta_k | mean %s |' % fnum(o['delta_summary']['fro_mean']))
    W('')

out = os.path.join(D, 'NUMBERS.md')
io.open(out, 'w', encoding='utf-8').write('\n'.join(L_) + '\n')
print('wrote %s (%d lines, %d bytes)' % (out, len(L_), os.path.getsize(out)))
